### ISSUE TITLE
MS Paint logo?

### ISSUE THREAD

**Issue by ArchdukeTim** [wpilibsuite/branding#4]
I feel that the complexity and time put into WPILib, as well as the number of people it services makes it deserving of a logo that is a bit more professional. 

Understandably a whole lot of time can't be dedicated to just a logo, but it may be worth it.

**Comment by calcmogul** [comment]
What kind of logo did you have in mind? I put in some time to design a logo as SVG whose files are in this repo, but I'm open to suggestions. I'm an engineer without formal graphic design experience afterall.

**Comment by ArchdukeTim** [comment]
I think something that isn't as matte/flat, and I think it's missing a few key elements [This logo](http://frc-pdr.readthedocs.io/en/latest/) shows different languages, as well as FRC. I think the WPILib logo should show both FRC, as well as WPI. The W kinda works, but I couldn't look at it and know "oh yeah, that's definitely wpilib.

**Comment by 333fred** [comment]
The problem with a logo like that is that it's waaay too busy. We purposefully tried to go with a simple logo that can be printed on things like t-shirts, business cards, and the like. It also needs to be able to look good on our repository, which is a relatively small image. This logo was designed to recognizable all the way down to the profile image on a slack group.

**Comment by ArchdukeTim** [comment]
That makes sense as well. I feel that there may be a halfway point though. If the colors were Red, white, and blue, like FIRST, or if instead of a hexagon and gear you had the square, triangle, and circle.

**Comment by Kevin-OConnor** [comment]
The WPILib logo intentionally steers clear of FIRST branding. I don't think this is something we currently see as an issue right now.

**Comment by ArchdukeTim** [comment]
Why though? 

The description of the wpilibsuite organization is "The official repositories of the WPILib Suite, a robotics software library used in the **FIRST Robotics Competition**"

**Comment by 333fred** [comment]
Yes, but we're not run by FIRST. Kevin is the only person employed by FIRST on the team, and while FIRST has a voice in development, and they may be the only customer, but they aren't in charge of the project. Having our logo be composed of FIRST colors or branding would imply a more concrete relationship than currently exists. Additionally, we don't want to be restricted by FIRST branding standards, which would be required if we used the triangle, circle, or square.

**Comment by ArchdukeTim** [comment]
Gotcha
